-- Migration 058: AI gateway trace records for observability and eval gates
-- Ticket: P1-E3-W7-S07-T03 (forge-ai-gateway-observability-and-eval-gates)
-- Creates ag_traces table for per-stage pipeline observability.
-- ag_key_audit (from T01) may not yet exist; ag_traces references key_id as a loose FK.
--
-- TraceStage: embed | retrieve | rerank | generate | policy
-- Privacy: tool input payload and error messages MUST be redacted via redact.ts before insert.

-- ─── Up migration ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS ag_traces (
  -- Primary key: UUID v4 generated by the application layer
  trace_id TEXT PRIMARY KEY NOT NULL,

  -- Tenant isolation (Cloud multi-tenancy; see Multi-Tenant Convention Wall in PPI)
  tenant_id TEXT NOT NULL,

  -- Reference to ag_key_audit.key_id (loose FK — ag_key_audit may be in a different migration)
  tool_id TEXT NOT NULL,

  -- Pipeline stage identifier: embed | retrieve | rerank | generate | policy
  stage TEXT NOT NULL CHECK (stage IN ('embed', 'retrieve', 'rerank', 'generate', 'policy')),

  -- Performance
  latency_ms INTEGER NOT NULL DEFAULT 0,

  -- Token usage and cost
  token_count INTEGER NOT NULL DEFAULT 0,
  cost_usd REAL NOT NULL DEFAULT 0.0,

  -- Model routing
  model_id TEXT, -- nullable: non-model stages (policy) have NULL

  -- Cache and error state
  cache_hit INTEGER NOT NULL DEFAULT 0 CHECK (cache_hit IN (0, 1)), -- SQLite boolean
  error_code TEXT, -- NULL on success; set to error code on failure

  -- Privacy: true if any PII pattern was matched and replaced in error_code or payload
  redacted INTEGER NOT NULL DEFAULT 0 CHECK (redacted IN (0, 1)),

  -- Timestamps
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

-- Indexes for common query patterns:
-- 1. Daily cost aggregate by tenant + model + date
CREATE INDEX IF NOT EXISTS idx_ag_traces_tenant_model_date
  ON ag_traces (tenant_id, model_id, date(created_at));

-- 2. Tool usage audit (ag_key_audit join)
CREATE INDEX IF NOT EXISTS idx_ag_traces_tool_id
  ON ag_traces (tool_id);

-- 3. Stage-level latency analysis
CREATE INDEX IF NOT EXISTS idx_ag_traces_stage_created
  ON ag_traces (stage, created_at);

-- 4. Error analysis
CREATE INDEX IF NOT EXISTS idx_ag_traces_error_code
  ON ag_traces (error_code) WHERE error_code IS NOT NULL;


-- ─── Down migration ───────────────────────────────────────────────────────────
-- To roll back: DROP TABLE IF EXISTS ag_traces;
-- Also remove associated indexes (they are dropped automatically with the table in SQLite).
--
-- NOTE: Down migration is provided below as a comment for Drizzle down() method reference.
-- To execute: DROP TABLE IF EXISTS ag_traces;
