// gateway.proto — GatewayService definition for clawde-intelligence.
//
// Purpose: Defines the gRPC surface (Complete, StreamComplete, Embed, Rerank,
//          Health) with grpc-gateway HTTP annotations for the REST mux on 8091.
// Ports:   gRPC 127.0.0.1:8090 | REST 127.0.0.1:8091
// Auth:    HMAC-SHA256 on all RPCs except /health (see internal/server/auth.go)
// SPORT:   REGISTRY-ENDPOINTS.md / REGISTRY-SERVICES.md
//
// NOTE: protoc-gen-go, protoc-gen-go-grpc, and protoc-gen-grpc-gateway are NOT
// installed in this environment. The generated Go stubs live in
// internal/server/gateway_grpc_gen.go (hand-written equivalents).
// Run `make proto` once those tools are installed to regenerate.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: gateway.proto

package server

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompleteRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Lane         string                 `protobuf:"bytes,1,opt,name=lane,proto3" json:"lane,omitempty"`
	Messages     []*Message             `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	SystemPrompt string                 `protobuf:"bytes,3,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	MaxTokens    int32                  `protobuf:"varint,4,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	WorkspaceId  string                 `protobuf:"bytes,5,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	RequestId    string                 `protobuf:"bytes,6,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Fields 7-9 reserved for future use.
	// Multimodal fields (MULTIMODAL lane — W16-S16-T03):
	Images        [][]byte `protobuf:"bytes,10,rep,name=images,proto3" json:"images,omitempty"`                                      // raw image bytes; max 5 images, max 10MB each
	ImageMimeType string   `protobuf:"bytes,11,opt,name=image_mime_type,json=imageMimeType,proto3" json:"image_mime_type,omitempty"` // shared MIME for all images: image/png|jpeg|gif|webp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteRequest) Reset() {
	*x = CompleteRequest{}
	mi := &file_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRequest) ProtoMessage() {}

func (x *CompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRequest.ProtoReflect.Descriptor instead.
func (*CompleteRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *CompleteRequest) GetLane() string {
	if x != nil {
		return x.Lane
	}
	return ""
}

func (x *CompleteRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *CompleteRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *CompleteRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *CompleteRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *CompleteRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CompleteRequest) GetImages() [][]byte {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *CompleteRequest) GetImageMimeType() string {
	if x != nil {
		return x.ImageMimeType
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CompleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	InputTokens   int32                  `protobuf:"varint,2,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens  int32                  `protobuf:"varint,3,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	Enriched      bool                   `protobuf:"varint,4,opt,name=enriched,proto3" json:"enriched,omitempty"`
	Provider      string                 `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
	Model         string                 `protobuf:"bytes,6,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteResponse) Reset() {
	*x = CompleteResponse{}
	mi := &file_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteResponse) ProtoMessage() {}

func (x *CompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteResponse.ProtoReflect.Descriptor instead.
func (*CompleteResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CompleteResponse) GetInputTokens() int32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *CompleteResponse) GetOutputTokens() int32 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *CompleteResponse) GetEnriched() bool {
	if x != nil {
		return x.Enriched
	}
	return false
}

func (x *CompleteResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CompleteResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type StreamCompleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lane          string                 `protobuf:"bytes,1,opt,name=lane,proto3" json:"lane,omitempty"`
	Messages      []*Message             `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	SystemPrompt  string                 `protobuf:"bytes,3,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,4,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,5,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,6,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamCompleteRequest) Reset() {
	*x = StreamCompleteRequest{}
	mi := &file_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamCompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamCompleteRequest) ProtoMessage() {}

func (x *StreamCompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamCompleteRequest.ProtoReflect.Descriptor instead.
func (*StreamCompleteRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *StreamCompleteRequest) GetLane() string {
	if x != nil {
		return x.Lane
	}
	return ""
}

func (x *StreamCompleteRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *StreamCompleteRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *StreamCompleteRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *StreamCompleteRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *StreamCompleteRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type StreamChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delta         string                 `protobuf:"bytes,1,opt,name=delta,proto3" json:"delta,omitempty"`
	Done          bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	Error         *GatewayError          `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamChunk) Reset() {
	*x = StreamChunk{}
	mi := &file_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamChunk) ProtoMessage() {}

func (x *StreamChunk) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamChunk.ProtoReflect.Descriptor instead.
func (*StreamChunk) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *StreamChunk) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

func (x *StreamChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *StreamChunk) GetError() *GatewayError {
	if x != nil {
		return x.Error
	}
	return nil
}

type EmbedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	ExpectedDim   int32                  `protobuf:"varint,2,opt,name=expected_dim,json=expectedDim,proto3" json:"expected_dim,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,3,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedRequest) Reset() {
	*x = EmbedRequest{}
	mi := &file_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedRequest) ProtoMessage() {}

func (x *EmbedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedRequest.ProtoReflect.Descriptor instead.
func (*EmbedRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *EmbedRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *EmbedRequest) GetExpectedDim() int32 {
	if x != nil {
		return x.ExpectedDim
	}
	return 0
}

func (x *EmbedRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *EmbedRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type EmbedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embedding     []float32              `protobuf:"fixed32,1,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedResponse) Reset() {
	*x = EmbedResponse{}
	mi := &file_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedResponse) ProtoMessage() {}

func (x *EmbedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedResponse.ProtoReflect.Descriptor instead.
func (*EmbedResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *EmbedResponse) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *EmbedResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *EmbedResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type RerankRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Documents     []string               `protobuf:"bytes,2,rep,name=documents,proto3" json:"documents,omitempty"`
	TopN          int32                  `protobuf:"varint,3,opt,name=top_n,json=topN,proto3" json:"top_n,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,4,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RerankRequest) Reset() {
	*x = RerankRequest{}
	mi := &file_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RerankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RerankRequest) ProtoMessage() {}

func (x *RerankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RerankRequest.ProtoReflect.Descriptor instead.
func (*RerankRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *RerankRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RerankRequest) GetDocuments() []string {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *RerankRequest) GetTopN() int32 {
	if x != nil {
		return x.TopN
	}
	return 0
}

func (x *RerankRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *RerankRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type RerankResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RankedIndices []int32                `protobuf:"varint,1,rep,packed,name=ranked_indices,json=rankedIndices,proto3" json:"ranked_indices,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RerankResponse) Reset() {
	*x = RerankResponse{}
	mi := &file_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RerankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RerankResponse) ProtoMessage() {}

func (x *RerankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RerankResponse.ProtoReflect.Descriptor instead.
func (*RerankResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *RerankResponse) GetRankedIndices() []int32 {
	if x != nil {
		return x.RankedIndices
	}
	return nil
}

func (x *RerankResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *RerankResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{9}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Providers     []*ProviderHealth      `protobuf:"bytes,2,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_gateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{10}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetProviders() []*ProviderHealth {
	if x != nil {
		return x.Providers
	}
	return nil
}

type ProviderHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Healthy       bool                   `protobuf:"varint,2,opt,name=healthy,proto3" json:"healthy,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderHealth) Reset() {
	*x = ProviderHealth{}
	mi := &file_gateway_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderHealth) ProtoMessage() {}

func (x *ProviderHealth) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderHealth.ProtoReflect.Descriptor instead.
func (*ProviderHealth) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{11}
}

func (x *ProviderHealth) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProviderHealth) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *ProviderHealth) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type GatewayError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ProviderError string                 `protobuf:"bytes,3,opt,name=provider_error,json=providerError,proto3" json:"provider_error,omitempty"`
	RetryAfter    int64                  `protobuf:"varint,4,opt,name=retry_after,json=retryAfter,proto3" json:"retry_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayError) Reset() {
	*x = GatewayError{}
	mi := &file_gateway_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayError) ProtoMessage() {}

func (x *GatewayError) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayError.ProtoReflect.Descriptor instead.
func (*GatewayError) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{12}
}

func (x *GatewayError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GatewayError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GatewayError) GetProviderError() string {
	if x != nil {
		return x.ProviderError
	}
	return ""
}

func (x *GatewayError) GetRetryAfter() int64 {
	if x != nil {
		return x.RetryAfter
	}
	return 0
}

type CompileContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Signals       *SessionSignals        `protobuf:"bytes,2,opt,name=signals,proto3" json:"signals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompileContextRequest) Reset() {
	*x = CompileContextRequest{}
	mi := &file_gateway_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileContextRequest) ProtoMessage() {}

func (x *CompileContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileContextRequest.ProtoReflect.Descriptor instead.
func (*CompileContextRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{13}
}

func (x *CompileContextRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *CompileContextRequest) GetSignals() *SessionSignals {
	if x != nil {
		return x.Signals
	}
	return nil
}

type SessionSignals struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ActiveFilePath string                 `protobuf:"bytes,1,opt,name=active_file_path,json=activeFilePath,proto3" json:"active_file_path,omitempty"`
	VisibleSymbols []string               `protobuf:"bytes,2,rep,name=visible_symbols,json=visibleSymbols,proto3" json:"visible_symbols,omitempty"`
	RecentDiff     string                 `protobuf:"bytes,3,opt,name=recent_diff,json=recentDiff,proto3" json:"recent_diff,omitempty"`
	LastError      string                 `protobuf:"bytes,4,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SessionSignals) Reset() {
	*x = SessionSignals{}
	mi := &file_gateway_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionSignals) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionSignals) ProtoMessage() {}

func (x *SessionSignals) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionSignals.ProtoReflect.Descriptor instead.
func (*SessionSignals) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{14}
}

func (x *SessionSignals) GetActiveFilePath() string {
	if x != nil {
		return x.ActiveFilePath
	}
	return ""
}

func (x *SessionSignals) GetVisibleSymbols() []string {
	if x != nil {
		return x.VisibleSymbols
	}
	return nil
}

func (x *SessionSignals) GetRecentDiff() string {
	if x != nil {
		return x.RecentDiff
	}
	return ""
}

func (x *SessionSignals) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type CompileContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContextBlock  string                 `protobuf:"bytes,1,opt,name=context_block,json=contextBlock,proto3" json:"context_block,omitempty"`
	Enriched      bool                   `protobuf:"varint,2,opt,name=enriched,proto3" json:"enriched,omitempty"`
	TokenCount    int32                  `protobuf:"varint,3,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
	CacheHit      bool                   `protobuf:"varint,4,opt,name=cache_hit,json=cacheHit,proto3" json:"cache_hit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompileContextResponse) Reset() {
	*x = CompileContextResponse{}
	mi := &file_gateway_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileContextResponse) ProtoMessage() {}

func (x *CompileContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileContextResponse.ProtoReflect.Descriptor instead.
func (*CompileContextResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{15}
}

func (x *CompileContextResponse) GetContextBlock() string {
	if x != nil {
		return x.ContextBlock
	}
	return ""
}

func (x *CompileContextResponse) GetEnriched() bool {
	if x != nil {
		return x.Enriched
	}
	return false
}

func (x *CompileContextResponse) GetTokenCount() int32 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

func (x *CompileContextResponse) GetCacheHit() bool {
	if x != nil {
		return x.CacheHit
	}
	return false
}

type IngestDocURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	DocType       string                 `protobuf:"bytes,3,opt,name=doc_type,json=docType,proto3" json:"doc_type,omitempty"` // code | markdown | docstring | comment (default markdown)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestDocURLRequest) Reset() {
	*x = IngestDocURLRequest{}
	mi := &file_gateway_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestDocURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestDocURLRequest) ProtoMessage() {}

func (x *IngestDocURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestDocURLRequest.ProtoReflect.Descriptor instead.
func (*IngestDocURLRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{16}
}

func (x *IngestDocURLRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *IngestDocURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *IngestDocURLRequest) GetDocType() string {
	if x != nil {
		return x.DocType
	}
	return ""
}

type IngestDocURLResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ChunksEnqueued int32                  `protobuf:"varint,1,opt,name=chunks_enqueued,json=chunksEnqueued,proto3" json:"chunks_enqueued,omitempty"`
	Skipped        bool                   `protobuf:"varint,2,opt,name=skipped,proto3" json:"skipped,omitempty"`
	Reason         string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IngestDocURLResponse) Reset() {
	*x = IngestDocURLResponse{}
	mi := &file_gateway_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestDocURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestDocURLResponse) ProtoMessage() {}

func (x *IngestDocURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestDocURLResponse.ProtoReflect.Descriptor instead.
func (*IngestDocURLResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{17}
}

func (x *IngestDocURLResponse) GetChunksEnqueued() int32 {
	if x != nil {
		return x.ChunksEnqueued
	}
	return 0
}

func (x *IngestDocURLResponse) GetSkipped() bool {
	if x != nil {
		return x.Skipped
	}
	return false
}

func (x *IngestDocURLResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_gateway_proto protoreflect.FileDescriptor

const file_gateway_proto_rawDesc = "" +
	"\n" +
	"\rgateway.proto\x12\n" +
	"gateway.v1\x1a\x1cgoogle/api/annotations.proto\"\x9c\x02\n" +
	"\x0fCompleteRequest\x12\x12\n" +
	"\x04lane\x18\x01 \x01(\tR\x04lane\x12/\n" +
	"\bmessages\x18\x02 \x03(\v2\x13.gateway.v1.MessageR\bmessages\x12#\n" +
	"\rsystem_prompt\x18\x03 \x01(\tR\fsystemPrompt\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x04 \x01(\x05R\tmaxTokens\x12!\n" +
	"\fworkspace_id\x18\x05 \x01(\tR\vworkspaceId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x06 \x01(\tR\trequestId\x12\x16\n" +
	"\x06images\x18\n" +
	" \x03(\fR\x06images\x12&\n" +
	"\x0fimage_mime_type\x18\v \x01(\tR\rimageMimeType\"7\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\xc2\x01\n" +
	"\x10CompleteResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12!\n" +
	"\finput_tokens\x18\x02 \x01(\x05R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x03 \x01(\x05R\foutputTokens\x12\x1a\n" +
	"\benriched\x18\x04 \x01(\bR\benriched\x12\x1a\n" +
	"\bprovider\x18\x05 \x01(\tR\bprovider\x12\x14\n" +
	"\x05model\x18\x06 \x01(\tR\x05model\"\xe2\x01\n" +
	"\x15StreamCompleteRequest\x12\x12\n" +
	"\x04lane\x18\x01 \x01(\tR\x04lane\x12/\n" +
	"\bmessages\x18\x02 \x03(\v2\x13.gateway.v1.MessageR\bmessages\x12#\n" +
	"\rsystem_prompt\x18\x03 \x01(\tR\fsystemPrompt\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x04 \x01(\x05R\tmaxTokens\x12!\n" +
	"\fworkspace_id\x18\x05 \x01(\tR\vworkspaceId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x06 \x01(\tR\trequestId\"g\n" +
	"\vStreamChunk\x12\x14\n" +
	"\x05delta\x18\x01 \x01(\tR\x05delta\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\x12.\n" +
	"\x05error\x18\x03 \x01(\v2\x18.gateway.v1.GatewayErrorR\x05error\"\x87\x01\n" +
	"\fEmbedRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12!\n" +
	"\fexpected_dim\x18\x02 \x01(\x05R\vexpectedDim\x12!\n" +
	"\fworkspace_id\x18\x03 \x01(\tR\vworkspaceId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"_\n" +
	"\rEmbedResponse\x12\x1c\n" +
	"\tembedding\x18\x01 \x03(\x02R\tembedding\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\"\x9a\x01\n" +
	"\rRerankRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1c\n" +
	"\tdocuments\x18\x02 \x03(\tR\tdocuments\x12\x13\n" +
	"\x05top_n\x18\x03 \x01(\x05R\x04topN\x12!\n" +
	"\fworkspace_id\x18\x04 \x01(\tR\vworkspaceId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\"i\n" +
	"\x0eRerankResponse\x12%\n" +
	"\x0eranked_indices\x18\x01 \x03(\x05R\rrankedIndices\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\"\x0f\n" +
	"\rHealthRequest\"b\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x128\n" +
	"\tproviders\x18\x02 \x03(\v2\x1a.gateway.v1.ProviderHealthR\tproviders\"]\n" +
	"\x0eProviderHealth\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\ahealthy\x18\x02 \x01(\bR\ahealthy\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x03R\tlatencyMs\"\x84\x01\n" +
	"\fGatewayError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0eprovider_error\x18\x03 \x01(\tR\rproviderError\x12\x1f\n" +
	"\vretry_after\x18\x04 \x01(\x03R\n" +
	"retryAfter\"p\n" +
	"\x15CompileContextRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x124\n" +
	"\asignals\x18\x02 \x01(\v2\x1a.gateway.v1.SessionSignalsR\asignals\"\xa3\x01\n" +
	"\x0eSessionSignals\x12(\n" +
	"\x10active_file_path\x18\x01 \x01(\tR\x0eactiveFilePath\x12'\n" +
	"\x0fvisible_symbols\x18\x02 \x03(\tR\x0evisibleSymbols\x12\x1f\n" +
	"\vrecent_diff\x18\x03 \x01(\tR\n" +
	"recentDiff\x12\x1d\n" +
	"\n" +
	"last_error\x18\x04 \x01(\tR\tlastError\"\x97\x01\n" +
	"\x16CompileContextResponse\x12#\n" +
	"\rcontext_block\x18\x01 \x01(\tR\fcontextBlock\x12\x1a\n" +
	"\benriched\x18\x02 \x01(\bR\benriched\x12\x1f\n" +
	"\vtoken_count\x18\x03 \x01(\x05R\n" +
	"tokenCount\x12\x1b\n" +
	"\tcache_hit\x18\x04 \x01(\bR\bcacheHit\"e\n" +
	"\x13IngestDocURLRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x19\n" +
	"\bdoc_type\x18\x03 \x01(\tR\adocType\"q\n" +
	"\x14IngestDocURLResponse\x12'\n" +
	"\x0fchunks_enqueued\x18\x01 \x01(\x05R\x0echunksEnqueued\x12\x18\n" +
	"\askipped\x18\x02 \x01(\bR\askipped\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason2\xfb\x05\n" +
	"\x0eGatewayService\x12f\n" +
	"\bComplete\x12\x1b.gateway.v1.CompleteRequest\x1a\x1c.gateway.v1.CompleteResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/gateway/complete\x12m\n" +
	"\x0eStreamComplete\x12!.gateway.v1.StreamCompleteRequest\x1a\x17.gateway.v1.StreamChunk\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/gateway/stream0\x01\x12Z\n" +
	"\x05Embed\x12\x18.gateway.v1.EmbedRequest\x1a\x19.gateway.v1.EmbedResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/gateway/embed\x12^\n" +
	"\x06Rerank\x12\x19.gateway.v1.RerankRequest\x1a\x1a.gateway.v1.RerankResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/gateway/rerank\x12[\n" +
	"\x06Health\x12\x19.gateway.v1.HealthRequest\x1a\x1a.gateway.v1.HealthResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/gateway/health\x12\x7f\n" +
	"\x0eCompileContext\x12!.gateway.v1.CompileContextRequest\x1a\".gateway.v1.CompileContextResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/gateway/compile_context\x12x\n" +
	"\fIngestDocURL\x12\x1f.gateway.v1.IngestDocURLRequest\x1a .gateway.v1.IngestDocURLResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/gateway/ingest_doc_urlB:Z8github.com/nself-org/clawde/intelligence/internal/serverb\x06proto3"

var (
	file_gateway_proto_rawDescOnce sync.Once
	file_gateway_proto_rawDescData []byte
)

func file_gateway_proto_rawDescGZIP() []byte {
	file_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_proto_rawDesc), len(file_gateway_proto_rawDesc)))
	})
	return file_gateway_proto_rawDescData
}

var file_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_gateway_proto_goTypes = []any{
	(*CompleteRequest)(nil),        // 0: gateway.v1.CompleteRequest
	(*Message)(nil),                // 1: gateway.v1.Message
	(*CompleteResponse)(nil),       // 2: gateway.v1.CompleteResponse
	(*StreamCompleteRequest)(nil),  // 3: gateway.v1.StreamCompleteRequest
	(*StreamChunk)(nil),            // 4: gateway.v1.StreamChunk
	(*EmbedRequest)(nil),           // 5: gateway.v1.EmbedRequest
	(*EmbedResponse)(nil),          // 6: gateway.v1.EmbedResponse
	(*RerankRequest)(nil),          // 7: gateway.v1.RerankRequest
	(*RerankResponse)(nil),         // 8: gateway.v1.RerankResponse
	(*HealthRequest)(nil),          // 9: gateway.v1.HealthRequest
	(*HealthResponse)(nil),         // 10: gateway.v1.HealthResponse
	(*ProviderHealth)(nil),         // 11: gateway.v1.ProviderHealth
	(*GatewayError)(nil),           // 12: gateway.v1.GatewayError
	(*CompileContextRequest)(nil),  // 13: gateway.v1.CompileContextRequest
	(*SessionSignals)(nil),         // 14: gateway.v1.SessionSignals
	(*CompileContextResponse)(nil), // 15: gateway.v1.CompileContextResponse
	(*IngestDocURLRequest)(nil),    // 16: gateway.v1.IngestDocURLRequest
	(*IngestDocURLResponse)(nil),   // 17: gateway.v1.IngestDocURLResponse
}
var file_gateway_proto_depIdxs = []int32{
	1,  // 0: gateway.v1.CompleteRequest.messages:type_name -> gateway.v1.Message
	1,  // 1: gateway.v1.StreamCompleteRequest.messages:type_name -> gateway.v1.Message
	12, // 2: gateway.v1.StreamChunk.error:type_name -> gateway.v1.GatewayError
	11, // 3: gateway.v1.HealthResponse.providers:type_name -> gateway.v1.ProviderHealth
	14, // 4: gateway.v1.CompileContextRequest.signals:type_name -> gateway.v1.SessionSignals
	0,  // 5: gateway.v1.GatewayService.Complete:input_type -> gateway.v1.CompleteRequest
	3,  // 6: gateway.v1.GatewayService.StreamComplete:input_type -> gateway.v1.StreamCompleteRequest
	5,  // 7: gateway.v1.GatewayService.Embed:input_type -> gateway.v1.EmbedRequest
	7,  // 8: gateway.v1.GatewayService.Rerank:input_type -> gateway.v1.RerankRequest
	9,  // 9: gateway.v1.GatewayService.Health:input_type -> gateway.v1.HealthRequest
	13, // 10: gateway.v1.GatewayService.CompileContext:input_type -> gateway.v1.CompileContextRequest
	16, // 11: gateway.v1.GatewayService.IngestDocURL:input_type -> gateway.v1.IngestDocURLRequest
	2,  // 12: gateway.v1.GatewayService.Complete:output_type -> gateway.v1.CompleteResponse
	4,  // 13: gateway.v1.GatewayService.StreamComplete:output_type -> gateway.v1.StreamChunk
	6,  // 14: gateway.v1.GatewayService.Embed:output_type -> gateway.v1.EmbedResponse
	8,  // 15: gateway.v1.GatewayService.Rerank:output_type -> gateway.v1.RerankResponse
	10, // 16: gateway.v1.GatewayService.Health:output_type -> gateway.v1.HealthResponse
	15, // 17: gateway.v1.GatewayService.CompileContext:output_type -> gateway.v1.CompileContextResponse
	17, // 18: gateway.v1.GatewayService.IngestDocURL:output_type -> gateway.v1.IngestDocURLResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_gateway_proto_init() }
func file_gateway_proto_init() {
	if File_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_proto_rawDesc), len(file_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_proto_depIdxs,
		MessageInfos:      file_gateway_proto_msgTypes,
	}.Build()
	File_gateway_proto = out.File
	file_gateway_proto_goTypes = nil
	file_gateway_proto_depIdxs = nil
}
